USE DATABASE FINTECH_DB;
USE SCHEMA RAW;
USE WAREHOUSE FINTECH_WH;

-- Raw Transactions Table
CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
    TRANSACTION_ID VARCHAR(100),
    CUSTOMER_ID VARCHAR(100),
    MERCHANT_ID VARCHAR(100),
    TRANSACTION_DATE TIMESTAMP,
    AMOUNT FLOAT,
    CURRENCY VARCHAR(10),
    TRANSACTION_TYPE VARCHAR(50),
    CHANNEL VARCHAR(50),
    STATUS VARCHAR(50),
    IS_FRAUD INT,
    FRAUD_REASON VARCHAR(500)
);

-- Raw Customers Table
CREATE OR REPLACE TABLE RAW.CUSTOMERS (
    CUSTOMER_ID VARCHAR(100),
    NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(500),
    ACCOUNT_TYPE VARCHAR(50),
    CREDIT_SCORE INT,
    STATE VARCHAR(10),
    JOIN_DATE DATE
);

-- Raw Merchants Table
CREATE OR REPLACE TABLE RAW.MERCHANTS (
    MERCHANT_ID VARCHAR(100),
    MERCHANT_NAME VARCHAR(200),
    CATEGORY VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(10),
    COUNTRY VARCHAR(10)
);