name: DBT Deploy Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install DBT
        run: |
          pip install dbt-snowflake

      - name: Create DBT profiles
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          dbt_project:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: wo98697.us-east-2.aws
                user: AISWARYALALICHETTI
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ACCOUNTADMIN
                warehouse: FINTECH_WH
                database: FINTECH_DB
                schema: ANALYTICS
                threads: 1
          EOF

      - name: Run DBT models
        run: |
          cd dbt_project
          dbt run

      - name: Run DBT tests
        run: |
          cd dbt_project
          dbt test
